name: asd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  scoped_model: ^2.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^0.4.12

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true


